name: ps
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/AdelDaniel/ps

environment:
  sdk: ^3.5.4

dependencies:
  test: ^1.24.0

dev_dependencies:
  lints: ^4.0.0
